set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_C_FLAGS "-march=native -O3 -funroll-loops")
set(VCPKG_CXX_FLAGS "-march=native -O3 -funroll-loops")

set(VCPKG_CMAKE_CONFIGURE_OPTIONS 
    "-DSPDLOG_NO_EXCEPTIONS=ON"
    "-DCMAKE_CXX_STANDARD=20")